language: python
os: linux
dist: bionic

jobs:
  include:
      - name: "Python 3.8 on Bionic Linux"

        os: linux
        dist: bionic

        python: 3.8
        
        services:
          - xvfb
          - docker
          - postgresql
        addons:
          firefox: latest

        before_install:
          - wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
          - mkdir geckodriver
          - tar -xzf geckodriver-v0.26.0-linux64.tar.gz -C geckodriver
          - export PATH=$PATH:$PWD/geckodriver

          - docker pull grafana/grafana
          - docker run -d -p 3000:3000 grafana/grafana
          - docker ps -a
        
        install:
          - pip3 install --upgrade pip
          - pip3 install -r requirements.txt
          - pip3 install -r test-requirements.txt
        
        before_script:
          - psql -c 'create database mercury;' -U postgres
          - python3 manage.py migrate
          - python3 manage.py collectstatic --noinput
        
        script:
          - black --check --diff .
          - flake8 . # modify .flake8 env file to update flake8 configuration
          - coverage run manage.py test # modify .coveragerc env file to update test configuration
        
        after_script:
          - coveralls
          - cat geckodriver.log

      - name: "Python 3.7 on macOS"

        os: osx
        osx_image: xcode11.3

        language: shell

        addons:
          homebrew:
            packages:
              - geckodriver
              - grafana
            casks:
              - firefox
            update: true

        before_install:
          - brew services start grafana

          # The following lines set up PostgreSQL on macOS worker
          - export PG_DATA=$(brew --prefix)/var/postgres
          - pg_ctl -w start -l postgres.log --pgdata ${PG_DATA}
          - createuser -s postgres
          - cat postgres.log
        
        install:
          - pip3 install --upgrade pip
          - pip3 install -r requirements.txt
          - pip3 install -r test-requirements.txt
        
        before_script:
          - psql -c 'create database mercury;' -U postgres
          - python3 manage.py migrate
          - python3 manage.py collectstatic --noinput
        
        script:
          - black --check --diff .
          - flake8 . # modify .flake8 env file to update flake8 configuration
          - coverage run manage.py test # modify .coveragerc env file to update test configuration
        
        after_script:
          - coveralls
          - cat geckodriver.log
      
      - name: "Onboard software tests for R-Pi"
      
        language: shell

        services:
            - docker
            - postgresql

        env:
          - REGISTRY_USER=nyutelemetryrobot
          # REGISTRY_PASS=...
          - secure: "qg8hTw5HJKUkrp0xJDmbhvXyvkfQyUrs/INjfn2qtPfn+VEeRC7ffud7/697LmILr1wBTxluXmqA31IvzwP7FvFg35ultvdMXzUQjZpsBcFK9bpu9jvnPAIcpK+jc/4l6wQCikpht+sZA+lgHSHvp+u/ZobSkNht6jP2gUzPbUzTqsMZhA6CNrIWfp6QusIE/G+aKEnBM04DjFYkEGAnb53qLUkmHtCyCE16Bthb2oy3cc1hoOtRgnAGVdvnyMxsnxLIHTIHzbKDQS0pX2eO3cL/0IUIVpuyVWmZxfKZksNFvae/KKl5KJchHYVUCCfSYMCXgt74qNNUuH+GPA6d3VjVhcBsW97CaYTGORBTdWV3xQ639Yn9Q5+r0GJkzkhX5gc6J2sUFv+HFW5/WoP1r8+oppUrontBnsyQ5t0MukkBK9woc4zuTGWyq66cyAgPA3dZVLSUdOlNf7cPFkN+sY24zHf9+FcFi/WAeS0pQ4g5wdgdyvm2FtNcxfvg5J8Jo34TzXTCfbXoaVc2FiwQQZnsCZtnUAzG2lNGj8uFT77d5T8+lXlDmxCZk4soNZp1Ax9AZiPmkRdwzkUYdAFKKoyO3V/3Ro5lhX+y1UVFoKyjka+h7qsD2r0hGxv2vFw2S1vlkql+69Oc5G9srlHSnbgqS7MOxsAq5SzhHxZi0Q8="

        install:
          - docker pull nyumotorsportstelemetryorg/mercury || true

          # prepare qemu for arm emulation on x64 hardware
          - docker run --rm --privileged multiarch/qemu-user-static:register --reset

          # build image
          - docker build --pull --cache-from nyumotorsportstelemetryorg/mercury --tag nyumotorsportstelemetryorg/mercury .

          - docker run -d --name test_pi nyumotorsportstelemetryorg/mercury
          
        script:
          # ensure that the server started up as expected
          - docker ps -a
          - docker ps | grep -q test_pi
        
        after_script:
          - docker images
        
        before_deploy:
          - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
        
        deploy:
          provider: script
          script: docker push nyumotorsportstelemetryorg/mercury
          on:
            branch: master
            repo: mercury-telemetry/mercury-telemetry